### ISSUE TITLE
Remove required dependency @nguniversal/express-engine

### ISSUE THREAD

**Issue by crhistianramirez** [Gorniv/ngx-universal#12]
Similar issue raised in ngx-cookie https://github.com/salemdar/ngx-cookie/issues/79

1. Consumers of this service that aren't doing server side rendering shouldn't have to download that package since it won't be used
2. Decouples which type of server must be used to do SSR. In this case we are tightly coupled to use an express server but what if someone wanted to use asp.net core or even something else? 

I suggest we remove [`CookieBackendService`](https://github.com/Gorniv/ngx-universal/blob/master/lib/src/cookie/cookie-backend.service.ts) from the source code and instead have it as *one of* several examples in a new `ssr-cookie-examples` directory. If we want to get fancy down the road we could have them as separate published packages.

**Comment by Gorniv** [comment]
I replace specific REQUEST and RESPONSE class to my class (NgxRequest and NgxResponce) for injecting.
