### ISSUE TITLE
Unhandled Promise rejection: StaticInjectorError(AppServerModule)[CookieService -> NgxRequest]

### ISSUE THREAD

**Issue by Luarb** [Gorniv/ngx-universal#15]
Hello ,
I have installed the latest Angular CLI and created an app also adding angular universal.
I am want to use the UniversalStorage injectable that you implemented on the Angular Universal Starter, but I am having this error:

> Unhandled Promise rejection: StaticInjectorError(AppServerModule)[CookieService -> NgxRequest]: 
  StaticInjectorError(Platform: core)[CookieService -> NgxRequest]: 
    NullInjectorError: No provider for NgxRequest! ; Zone: <root> ; Task: Promise.then ; Value: { NullInjectorError: StaticInjectorError(AppServerModule)[CookieService -> NgxRequest]: 
  StaticInjectorError(Platform: core)[CookieService -> NgxRequest]: 
    NullInjectorError: No provider for NgxRequest!
    at NullInjector.get (/home/www/ANGULAR STARER/dist/server/main.js:41073:27)
    at resolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55990:24)
    at tryResolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55916:16)
    at StaticInjector.get (/home/www/ANGULAR STARER/dist/server/main.js:55766:20)
    at resolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55990:24)
    at tryResolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55916:16)
    at StaticInjector.get (/home/www/ANGULAR STARER/dist/server/main.js:55766:20)
    at resolveNgModuleDep (/home/www/ANGULAR STARER/dist/server/main.js:66953:29)
    at _createClass (/home/www/ANGULAR STARER/dist/server/main.js:67025:29)
    at _createProviderInstance (/home/www/ANGULAR STARER/dist/server/main.js:66986:26)
  name: 'NullInjectorError',
  ngTempTokenPath: null,
  ngTokenPath: [ 'CookieService', [Function: NgxRequest] ] } NullInjectorError: StaticInjectorError(AppServerModule)[CookieService -> NgxRequest]: 
  StaticInjectorError(Platform: core)[CookieService -> NgxRequest]: 
    NullInjectorError: No provider for NgxRequest!
    at NullInjector.get (/home/www/ANGULAR STARER/dist/server/main.js:41073:27)
    at resolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55990:24)
    at tryResolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55916:16)
    at StaticInjector.get (/home/www/ANGULAR STARER/dist/server/main.js:55766:20)
    at resolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55990:24)
    at tryResolveToken (/home/www/ANGULAR STARER/dist/server/main.js:55916:16)
    at StaticInjector.get (/home/www/ANGULAR STARER/dist/server/main.js:55766:20)
    at resolveNgModuleDep (/home/www/ANGULAR STARER/dist/server/main.js:66953:29)
    at _createClass (/home/www/ANGULAR STARER/dist/server/main.js:67025:29)
    at _createProviderInstance (/home/www/ANGULAR STARER/dist/server/main.js:66986:26)

**app.server.module.ts :**

import { NgModule, ViewEncapsulation, Component } from '@angular/core';
import { ServerModule, ServerTransferStateModule } from '@angular/platform-server';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { ModuleMapLoaderModule } from '@nguniversal/module-map-ngfactory-loader';
import { TranslatesServerModule } from '@shared/translates/translates-server';
import { App } from './app.component';
import { AppModule } from './app.module';
import { CookieService, CookieBackendService, CookieModule } from '@gorniv/ngx-universal';

@NgModule({
  imports: [
    // AppModule - FIRST!!!
    AppModule,
    ServerModule,
    NoopAnimationsModule,
    ServerTransferStateModule,
    ModuleMapLoaderModule,
    TranslatesServerModule,
  ],
  bootstrap: [App],
  providers: [
    { provide: CookieService, useClass: CookieBackendService },
  ],
})
export class AppServerModule { }

**server.ts:**

import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import { enableProdMode } from '@angular/core';
import * as express from 'express';
import * as cookieparser from 'cookie-parser';
import { join } from 'path';
import { NgxRequest, NgxResponce } from '@gorniv/ngx-universal';
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';

const app = express();
const appLocale = 'it';
const PORT = process.env.PORT || 4500;
const DIST_FOLDER = join(process.cwd(), 'dist');
const domino = require('domino');
const fs = require('fs');
const path = require('path');
const compression = require('compression');
const template = fs.readFileSync(path.join(DIST_FOLDER, 'browser', 'index.html')).toString();
const win = domino.createWindow(template);
const { AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap } = require('./dist/server/main');

enableProdMode();

app.use(compression());
app.use(cookieparser());

var mcache = require('memory-cache');
var MobileDetect = require('mobile-detect');

global['appLocale'] = appLocale;
global['window'] = win;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
global['Event'] = win.Event;
global['Event']['prototype'] = win.Event.prototype;
global['document'] = win.document;
global['CSS'] = null;
global['google'] = null;

var cache = (duration) => {
  return (req, res, next) => {

    var md = new MobileDetect(req.headers['user-agent']);
    var device = md.mobile() ? "mobile" : "desktop";
    let key = "__express_" + device + "__" + req.url;

    let cachedBody = mcache.get(key);

    if (cachedBody) {
      res.send(cachedBody)

      return;

    } else {

      res.sendResponse = res.send;
      res.send = (body) => {
        mcache.put(key, body, duration * 1000);
        res.sendResponse(body);
      }
      next();
    }

  }
}

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP),
  ]
}));

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, 'browser'));
app.get('*.*', express.static(join(DIST_FOLDER, 'browser'), {
  maxAge: '1y'
}));

app.get('*', cache(3600), function (req, res) {

  const originalUrl = decodeURI(req.originalUrl);
  const http = req.headers['x-forwarded-proto'] === undefined ? 'http' : req.headers['x-forwarded-proto'];

  if (originalUrl.match(/[A-Z]/) !== null) {
    res.redirect(301, 'https' + '://' + req.get('host') + req.originalUrl.toLowerCase());
  }

  res.setHeader('Cache-Control', 'public, max-age=3600'); // cache header
  res.setHeader("Expires", new Date(Date.now() + 2592000000).toUTCString());

  res.render('index', {
    req: req,
    res: res,
    providers: [
      {
        provide: REQUEST,
        useValue: req,
      },
      {
        provide: RESPONSE,
        useValue: res,
      },
      {
        provide: NgxRequest,
        useValue: req,
      },
      {
        provide: NgxResponce,
        useValue: res,
      },
      {
        provide: 'ORIGIN_URL',
        useValue: `${http}://${req.headers.host}`,
      },
    ],
  },
    (err, html) => {
      if (!!err) {
        throw err;
      }

      console.timeEnd(`GET: ${originalUrl}`);
      res.send(html);
    });
});

app.listen(PORT, () => {
  console.log(`Node Express server listening on http://localhost:${PORT}`);
});

**package.json:**

> {
  "name": "angular-graphql-mongodb",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run angular-graphql-mongodb:server:production --bundleDependencies all"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.7",
    "@angular/common": "~8.2.7",
    "@angular/compiler": "~8.2.7",
    "@angular/core": "~8.2.7",
    "@angular/forms": "~8.2.7",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "~8.2.7",
    "@angular/platform-browser-dynamic": "~8.2.7",
    "@angular/platform-server": "~8.2.7",
    "@angular/router": "~8.2.7",
    "@angular/service-worker": "^8.2.7",
    "@gorniv/ngx-universal": "^2.0.1",
    "@nguniversal/common": "^8.1.1",
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "@ngx-meta/core": "^7.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "apollo-angular": "^1.7.0",
    "apollo-angular-link-http": "^1.6.0",
    "apollo-cache-inmemory": "^1.3.2",
    "apollo-client": "^2.6.0",
    "apollo-link": "^1.2.11",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.4",
    "domino": "^2.1.3",
    "express": "^4.15.2",
    "fs": "0.0.1-security",
    "graphql": "^14.3.1",
    "graphql-tag": "^2.10.0",
    "jquery": "^3.4.1",
    "memory-cache": "^0.2.0",
    "mobile-detect": "^1.4.4",
    "ng-simple-slideshow": "^1.2.9",
    "ng2-select": "^2.0.0",
    "ngx-captcha": "^7.0.0",
    "ngx-cookie-service": "^2.2.0",
    "ngx-device-detector": "^1.3.11",
    "ngx-mydatepicker": "^2.4.9",
    "ngx-owl-carousel-o": "^2.0.1",
    "ngx-toastr": "^10.2.0",
    "path": "^0.12.7",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.5",
    "@angular/cli": "~8.3.5",
    "@angular/compiler-cli": "~8.2.7",
    "@angular/language-service": "~8.2.7",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack-cli": "^3.1.0"
  }
}

**Comment by Gorniv** [comment]
are you use 'prerender.ts' file ?

**Comment by Luarb** [comment]
No, I am not using prerender.ts file

**Comment by Luarb** [comment]
You can recreate the problem like this :
Create a new Anguar app using the latest CLI:

>  ng new angular-unversal

Add angular universal : 

> ng add @nguniversal/express-engine --clientProject angular.io-example

And then just add your dependency  "@gorniv/ngx-universal" and use it on a component

**Comment by Luarb** [comment]
I found out after making some tests that it has a connection with this line of code: 
```
const { AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap } = require('./dist/server/main');
```

If I do it the way you import this modules : 
```
import { ngExpressEngine } from '@nguniversal/express-engine';
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');
```

Then I get this error : 

> No NgModule metadata found for '[object Object]'

**Comment by Luarb** [comment]
Also updating the ts configs and webpak config did the same error.

**Comment by bri1990** [comment]
same error it happends after I run:

node prerender.js

I get the following error:

> Unhandled Promise rejection: StaticInjectorError[CookieService -> NgxRequest]: 
  StaticInjectorError(Platform: core)[CookieService -> NgxRequest]: 
    NullInjectorError: No provider for NgxRequest! ; Zone: <root> ; Task: Promise.then ; Value: { NullInjectorError: StaticInjectorError[CookieService -> NgxRequest]: 
  StaticInjectorError(Platform: core)[CookieService -> NgxRequest]: 
    NullInjectorError: No provider for NgxRequest!
    at NullInjector.get (webpack:///./node_modules/@angular/core/fesm5/core.js?:1155:25)
    at resolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12347:24)
    at tryResolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12291:16)
    at StaticInjector.get (webpack:///./node_modules/@angular/core/fesm5/core.js?:12193:20)
    at resolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12347:24)
    at tryResolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12291:16)
    at StaticInjector.get (webpack:///./node_modules/@angular/core/fesm5/core.js?:12193:20)
    at resolveNgModuleDep (webpack:///./node_modules/@angular/core/fesm5/core.js?:20663:29)
    at _createClass (webpack:///./node_modules/@angular/core/fesm5/core.js?:20712:29)
    at _createProviderInstance (webpack:///./node_modules/@angular/core/fesm5/core.js?:20680:26)
  name: 'NullInjectorError',
  ngTempTokenPath: null,
  ngTokenPath: [ 'CookieService', [Function: NgxRequest] ] } NullInjectorError: StaticInjectorError[CookieService -> NgxRequest]: 
  StaticInjectorError(Platform: core)[CookieService -> NgxRequest]: 
    NullInjectorError: No provider for NgxRequest!
    at NullInjector.get (webpack:///./node_modules/@angular/core/fesm5/core.js?:1155:25)
    at resolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12347:24)
    at tryResolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12291:16)
    at StaticInjector.get (webpack:///./node_modules/@angular/core/fesm5/core.js?:12193:20)
    at resolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12347:24)
    at tryResolveToken (webpack:///./node_modules/@angular/core/fesm5/core.js?:12291:16)
    at StaticInjector.get (webpack:///./node_modules/@angular/core/fesm5/core.js?:12193:20)
    at resolveNgModuleDep (webpack:///./node_modules/@angular/core/fesm5/core.js?:20663:29)
    at _createClass (webpack:///./node_modules/@angular/core/fesm5/core.js?:20712:29)
    at _createProviderInstance (webpack:///./node_modules/@angular/core/fesm5/core.js?:20680:26)

**Comment by Luarb** [comment]
I found the solution. We need to export this from the main.server.ts
```
export { NgxRequest, NgxResponce } from '@gorniv/ngx-universal';
export { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
```

and then import then via require : 
`const { AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap,  NgxRequest, NgxResponce, REQUEST, RESPONSE } = require('./dist/server/main');`

And finally : 

```
res.render('index', {
    req: req,
    res: res,
    providers: [{
            provide: REQUEST,
            useValue: req,
        },
        {
            provide: RESPONSE,
            useValue: res,
        },
        {
            provide: NgxRequest,
            useValue: req,
        },
        {
            provide: NgxResponce,
            useValue: res,
        },
        {
            provide: 'ORIGIN_URL',
            useValue: $ {
                    http
                }: //${req.headers.host},
        },
    ],
},
(err, html) => {
    if (!!err) {
        throw err;
    }

    console.timeEnd(`GET: ${originalUrl}`);
    res.send(html);
});

```

**Comment by bri1990** [comment]
@Luarb well done! your solution worked.  Thank you!


And for those that use `node prerender.js` you also need to update the previous render in the prerender.ts file

added to `prerender.ts` file:

`const { AppServerModuleNgFactory, LAZY_MODULE_MAP, NgxRequest, NgxResponce } = require(`./dist-server/main.${hash}`);`

and 

`  // Writes rendered HTML to index.html, replacing the file if it already exists.
  previousRender = previousRender
    .then((_) =>
      renderModuleFactory(AppServerModuleNgFactory, {
        document: index,
        url: route,
        extraProviders: [
          provideModuleMap(LAZY_MODULE_MAP),
          {
            provide: REQUEST,
            useValue: { cookie: '', headers: {} },
          },
          {
            provide: NgxRequest,
            useValue: { cookie: '', headers: {} },
          },
          {
            provide: NgxResponce,
            useValue: {},
          },
          {
            provide: RESPONSE,
            useValue: {},
          },
          {
            provide: 'ORIGIN_URL',
            useValue: environment.host,
          },
        ],
      }),
    )
    .then((html) => writeFileSync(join(fullPath, 'index.html'), html));`
