### ISSUE TITLE
get add semicolon

### ISSUE THREAD

**Issue by Gorniv** [Gorniv/ngx-universal#2]
bytheway we got bonus ; semicolon
this.cookieService.put('something', 'values');
this.cookieService.get('something'); // values; isn't it supposed to be just values?

**Comment by esdegan50000** [comment]
this.cookieService.getAll() also return extra ; semicolon foreach values

on server.ts req.cookies was right, return as expected without ; semicolon

**Comment by esdegan50000** [comment]
whether any update for this issues?
getAll() also have extra semicolon on each values

cheers

**Comment by Gorniv** [comment]
try v1.2.1
