### ISSUE TITLE
Can you add the sameSite option?

### ISSUE THREAD

**Issue by BruneXX** [Gorniv/ngx-universal#31]
Hi Gorniv, 

I saw a firefox warning that it says that the cookie will be rejected soon if the attribute sameSite is not set, I was wondering if you can add that attribute in your code, are you still maintaining this repository?

Thanks!

**Comment by puneetverma05** [comment]
+1

**Comment by puneetverma05** [comment]
@BruneXX  can we try to add PR? le me look into the lib

**Comment by BruneXX** [comment]
Hi @puneetverma05 yep, I can take a look and try to add that feature, I’ll try to find the time to do this.

**Comment by BruneXX** [comment]
@puneetverma05 It seems that this repo is unmaintained, there're 10 pull request opened so far... I think we should fork and make our own mofifications..

**Comment by puneetverma05** [comment]
@BruneXX  I did added the sameSite option only testing required
https://github.com/puneetverma05/ngx-universal

**Comment by BruneXX** [comment]
Excellent!, thank you @puneetverma05

**Comment by puneetverma05** [comment]
> Excellent!, thank you @puneetverma05

just figuring out to use this in our project as a branch ref in package.json but it requires to have build dir.. that means.. need to refactor imports as well or last option is to have this published as npm package

**Comment by BruneXX** [comment]
Hi @puneetverma05 I've already do that, check here: https://www.npmjs.com/package/ngxc-universal
but I'm still testing it, for now after some tests, is not setting the **SameSite=[Strict|Lax|None]** just an empty SameSite option. I'm looking into it.

**Comment by puneetverma05** [comment]
@BruneXX  I tested its working fine , FYI when setting  `SameSite="none" ` it should be with `Secure=true` (send over https only)

**Comment by BruneXX** [comment]
Hi @puneetverma05 yes I’m using secure option for all the cookies I set, did you installed the 1.0.2 version of my forked package?

**Comment by puneetverma05** [comment]
@BruneXX Yes 1.0.2

**Comment by BruneXX** [comment]
Hi @puneetverma05 I think we can close this issue since we've resolved this creating or own repository, for those that need to set sameSite option can use my package from here: https://www.npmjs.com/package/ngxc-universal 
also if anyone needs any extra option I'll maintain that package so, feel free to request the feature that you want and I'll try to add it as soon as I can.
